# SafeCoin QT wallet Snapcraft build By Cameron Green - Team Safe
# Alpha Build, not stable
# Thanks to Carsen Klock from Denarius for help and code thats unique to cryptocurrencies
name: safecoinwallet # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.12' # just for humans, typically '1.2+git' or '1.3.2'
summary: safecoinwallet, currently without safecoind daemon # 79 char long summary
description: |
  This is the QT-based wallet for SafeCoin, without the daemon, so you must install the daemon separately

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  safecoinwallet:
    plugin: qmake
    source: .
    qt-version: qt5
    after: [desktop-qt5]
    build-packages:
      - git
      - qt5-default
      - qt5-qmake
      - libqt5websockets5-dev
      - qtcreator
      - g++
      - make
    stage-packages:
      - libdouble-conversion1
      - libfreetype6
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libharfbuzz0b
      - libicu60
      - libpng16-16
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5websockets5
      - libqt5widgets5
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
    
    override-build: |
      qmake safe-qt-wallet.pro CONFIG+=debug
      make -j2
      cp safecoinwallet $SNAPCRAFT_PART_INSTALL/bin

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
    organize:
      /bin: bin/desktop-qt5/bin 

  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme
  desktop:
    source: snap/gui 
    plugin: dump
  hooks:
    plugin: dump
    source: hooks/
    #organize:
      #bin/:snap/hooks/
hooks:
  install:
    plugs: [network, network-bind]
  post-refresh:
    plugs: [network, network-bind]
  configure:
    plugs: [network, network-bind]
apps:
  safecoinwallet:
    command: desktop-launch $SNAP/bin/safecoinwallet
    plugs: [home, network, network-bind, unity7, wayland, desktop-legacy, desktop, x11, gsettings]
    desktop: safecoinwallet.desktop
    environment:
      QT_QPA_PLATFORMTHEME: gtk3
      XDG_DATA_DIRS: $SNAP_USER_DATA:/var/lib/snapd/desktop:$XDG_DATA_DIRS
      HOME: $SNAP_USER_COMMON
      XDG_DATA_DIRS: $SNAP_USER_DATA:/var/lib/snapd/desktop:$XDG_DATA_DIRS
      # Override HOME so the datadir is located at
      # ~/snap/safecoinwallet/common/.safecoinwallet/ instead of
      # ~/snap/safecoinwallet/current/.safecoinwallet/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983  thanks to Carsen for figuring this out
