# SafeCoin QT wallet Snapcraft build By Cameron Green - Team Safe
# Alpha Build, not stable
# Thanks to Carsen Klock from Denarius for help and code thats unique to cryptocurrencies
name: safewallet # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.12' # just for humans, typically '1.2+git' or '1.3.2'
summary: SafeCoin QT wallet, very alpha. Don't install unless you are a tester # 79 char long summary
description: |
  This is the QT-based wallet for SafeCoin still in alpha test phase

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  safewallet:
    plugin: qmake
    source: https://github.com/sandsunsurf/safecoinwallet.git
    source-type: git
    qt-version: qt5
    after: [openssl]
    organize: 
      bin: safewalletbin/bin
    build-packages:
      - git
      - qt5-default
      - qt5-qmake
      - libqt5websockets5-dev
      - qtcreator
      - g++
      - make
    stage-packages:
      - libdouble-conversion1
      - libfreetype6
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libharfbuzz0b
      - libicu60
      - libpng16-16
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5websockets5
      - libqt5widgets5
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
    
    override-build: |
      qmake safe-qt-wallet.pro CONFIG+=debug
      make -j4
      sudo cp $SNAPCRAFT_PART_BUILD/safecoinwallet $SNAPCRAFT_PART_INSTALL/bin
  daemon:
     #See 'snapcraft plugins'
    plugin: nil
    source: https://github.com/sandsunsurf/safecoin.git
    source-type: git 
    build-packages:
      - build-essential
      - pkg-config
      - libc6-dev
      - m4
      - g++-multilib
      - autoconf
      - libtool
      - ncurses-dev
      - unzip
      - git
      - python
      - python-zmq
      - zlib1g-dev
      - wget
      - libcurl4-gnutls-dev
      - bsdmainutils
      - automake
      - curl
      - bc 
      - dc 
      - jq
      - libboost-all-dev
    stage-packages:
      - build-essential
      - pkg-config
      - libc6-dev
      - m4
      - g++-multilib
      - autoconf
      - libtool
      - ncurses-dev
      - unzip
      - git
      - python
      - python-zmq
      - zlib1g-dev
      - wget
      - libcurl4-gnutls-dev
      - bsdmainutils
      - automake
      - curl
      - bc 
      - dc 
      - jq
      - libboost-all-dev
    override-build: |
      OPENSSL_INCLUDE_PATH=/usr/local/ssl/include OPENSSL_LIB_PATH=/usr/local/ssl/lib
      ./zcutil/build.sh -j4
      cp $SNAPCRAFT_PART_BUILD/src/safecoind $SNAPCRAFT_PART_INSTALL/bin/
    organize:
      bin: daemonbin/bin
  openssl:
    plugin: nil
    source: https://www.openssl.org/source/openssl-1.0.1j.tar.gz
    build-packages:
      - g++
      - build-essential
      - libtool
    override-build: |
      echo "Downgrading OpenSSL to 1.0.1j"
      sudo ./config
      sudo make
      echo "Make depends OpenSSL to 1.0.1j"
      sudo make depend
      echo "Make install OpenSSL to 1.0.1j"
      sudo make install
      echo "Linking OpenSSL to 1.0.1j"
      sudo ln -sf /usr/local/ssl/bin/openssl `which openssl`
  qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    organize:
      bin: qtbin/bin
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme
  desktop: 
    source: https://github.com/sandsunsurf/safecoinwallet.git
    source-subdir: /gui 
    plugin: dump
    prime:
      - gui/
  hooks:
    plugin: dump
    source: hooks/
    organize:
      bin/: snap/hooks/
hooks:
  install:
    plugs: [network, network-bind]
  post-refresh:
    plugs: [network, network-bind]
  configure:
    plugs: [network, network-bind]
apps:
  safewallet:
    command: desktop-launch $SNAP/bin/safecoinwallet
    plugs: [home, network, network-bind, unity7, wayland, desktop-legacy, desktop, x11, gsettings]
    desktop: gui/safecoinwallet.desktop
    environment:
      QT_QPA_PLATFORMTHEME: gtk3
      XDG_DATA_DIRS: $SNAP_USER_DATA:/var/lib/snapd/desktop:$XDG_DATA_DIRS
      HOME: $SNAP_USER_COMMON
      
      # Override HOME so the datadir is located at
      # ~/snap/safecoinwallet/common/.safecoinwallet/ instead of
      # ~/snap/safecoinwallet/current/.safecoinwallet/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983  thanks to Carsen for sending me this direction
  daemon:
    command: bin/safecoind
    plugs: [home, network, network-bind]
    environment: 
      HOME: $SNAP_USER_COMMON
      XDG_DATA_DIRS: $SNAP_USER_DATA:/var/lib/snapd/desktop:$XDG_DATA_DIRS
  d:
    command: bin/safecoind
    plugs: [home,network,network-bind]
    daemon: forking
    environment:
      HOME: $SNAP_USER_COMMON
      XDG_DATA_DIRS: $SNAP_USER_DATA:/var/lib/snapd/desktop:$XDG_DATA_DIRS
